language: java

before_script:
  - echo $HOME
  - echo $JAVA_OPTS

jdk:
  - oraclejdk8

os:
  - linux

install: true
script:
  - ./gradlew build
  - bash <(curl -s https://codecov.io/bash)
  only:
  - master