language: java

jdk:
  - oraclejdk8

addons:
  ssh_known_hosts:
    - $HOST_IP

before_install:
  - sudo apt-get install sshpass

script:
  - ./gradlew build

after_success:
  - ./deploy.sh

notifications:
  email:
    - ysg0316@naver.com
    - varian.k.lee@gmail.com